### ISSUE TITLE
Does not work with ADMIN_PATH and STRAPI_ADMIN_BACKEND_URL

### ISSUE THREAD

**Issue by ilnytskyi** [boazpoolman/strapi-plugin-sitemap#163]
### Describe the bug

I run admin on different domain than main app.
```
ADMIN_PATH=/admin
STRAPI_ADMIN_BACKEND_URL=https://some.secret.domain/
```

### Steps to reproduce the behavior

1. Install strapi on different domain
2. Open settings page `/admin/settings/sitemap`
3. Page is broken as url does not contain admin path. Just base url

### Expected behavior

Settings page working correctly

### Screenshots

![image](https://github.com/boazpoolman/strapi-plugin-sitemap/assets/3192770/d0caabee-b038-4a23-b5a4-fa16132e72ef)

### Code snippets

in .env 

```
ADMIN_PATH=/admin
STRAPI_ADMIN_BACKEND_URL=https://some.secret.domain/
```

### System

- Node.js version: v20
- NPM version:
- Strapi version:
- Plugin version:
- Database:
- Operating system:

### Additional context

JS error 
```
[2024-03-13 22:17:12.818] error: Malicious Path
BadRequestError: Malicious Path
    at resolvePath (/app/path/node_modules/resolve-path/index.js:78:11)
    at send (/app/path/node_modules/koa-send/index.js:81:10)
    at serve (/app/path/node_modules/koa-static/index.js:66:13)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async returnBodyMiddleware (/app/path/node_modules/@strapi/strapi/dist/services/server/compose-endpoint.js:42:18)
    at async policiesMiddleware (/app/path/node_modules/@strapi/strapi/dist/services/server/policy.js:15:5)
    at async /app/path/node_modules/@strapi/strapi/dist/services/server/compose-endpoint.js:27:12
    at async /app/path/node_modules/@strapi/strapi/dist/middlewares/body.js:45:9
    at async /app/path/node_modules/@strapi/strapi/dist/middlewares/powered-by.js:9:5
    at async cors (/app/path/node_modules/@koa/cors/index.js:61:32)
```

**Comment by ilnytskyi** [comment]
UPD: 

this is st**id strapi issue related to not handling base url concatenation correctly if provided with trailing slash.

So instead of 
```
STRAPI_ADMIN_BACKEND_URL=https://some.secret.domain/
```

use 

```
STRAPI_ADMIN_BACKEND_URL=https://some.secret.domain
```

Then plugin url will not contain double slashes

```
https://some.secret.domain//sitemap/settings/  --> https://some.secret.domain/sitemap/settings/
```

But to be honest, it would be much simpler to allow use any base URL overrides in the plugin than playing with strapi url.
https://github.com/boazpoolman/strapi-plugin-sitemap/issues/127#issuecomment-1646578897

I am closing the issue as it's not directly related to this plugin but it's many small things that need some improvement
