### ISSUE TITLE
[BUG] Error with Strapi 4.3.2

### ISSUE THREAD

**Issue by SalahAdDin** [boazpoolman/strapi-plugin-sitemap#93]
### Describe the bug
Somehow, when trying to get into the Sitemap view we are getting this problem:
```
[2022-08-07 23:30:00.122] error: [strapi-plugin-sitemap]: Something went wrong while trying to build the SitemapStream. TypeError [ERR_INVALID_URL]: Invalid URL: 
[2022-08-07 23:31:00.132] error: [strapi-plugin-sitemap]: Something went wrong while trying to build the SitemapStream. TypeError [ERR_INVALID_URL]: Invalid URL: 
[2022-08-07 23:32:00.149] error: [strapi-plugin-sitemap]: Something went wrong while trying to build the SitemapStream. TypeError [ERR_INVALID_URL]: Invalid URL: 
This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason:
Error
    at Object.createSitemap (/srv/app/node_modules/strapi-plugin-sitemap/server/services/core.js:248:11)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason:
Error
    at Object.createSitemap (/srv/app/node_modules/strapi-plugin-sitemap/server/services/core.js:248:11)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason:
Error
    at Object.createSitemap (/srv/app/node_modules/strapi-plugin-sitemap/server/services/core.js:248:11)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason:
Error
    at Object.createSitemap (/srv/app/node_modules/strapi-plugin-sitemap/server/services/core.js:248:11)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason:
Error
    at Object.createSitemap (/srv/app/node_modules/strapi-plugin-sitemap/server/services/core.js:248:11)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason:
Error
    at Object.createSitemap (/srv/app/node_modules/strapi-plugin-sitemap/server/services/core.js:248:11)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason:
Error
    at Object.createSitemap (/srv/app/node_modules/strapi-plugin-sitemap/server/services/core.js:248:11)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason:
Error
    at Object.createSitemap (/srv/app/node_modules/strapi-plugin-sitemap/server/services/core.js:248:11)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason:
Error
    at Object.createSitemap (/srv/app/node_modules/strapi-plugin-sitemap/server/services/core.js:248:11)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason:
Error
    at Object.createSitemap (/srv/app/node_modules/strapi-plugin-sitemap/server/services/core.js:248:11)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason:
Error
    at Object.createSitemap (/srv/app/node_modules/strapi-plugin-sitemap/server/services/core.js:248:11)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
(node:95) Warning: [deprecated] In future versions, Strapi will stop reading directly from the environment variable API_TOKEN_SALT. Please set apiToken.salt in config/admin.js instead.
For security reasons, keep storing the secret in an environment variable and use env() to read it in config/admin.js (ex: `apiToken: { salt: env('API_TOKEN_SALT') }`). See https://docs.strapi.io/developer-docs/latest/setup-deployment-guides/configurations/optional/environment.html#configuration-using-environment-variables.
(Use `node --trace-warnings ...` to show where the warning was created)
This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason:
Error
    at Object.createSitemap (/srv/app/node_modules/strapi-plugin-sitemap/server/services/core.js:248:11)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason:
Error
    at Object.createSitemap (/srv/app/node_modules/strapi-plugin-sitemap/server/services/core.js:248:11)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason:
Error
[2022-08-07 23:33:00.198] error: [strapi-plugin-sitemap]: Something went wrong while trying to build the SitemapStream. TypeError [ERR_INVALID_URL]: Invalid URL: 
[2022-08-07 23:34:00.188] error: [strapi-plugin-sitemap]: Something went wrong while trying to build the SitemapStream. TypeError [ERR_INVALID_URL]: Invalid URL: 
[2022-08-07 23:35:00.187] error: [strapi-plugin-sitemap]: Something went wrong while trying to build the SitemapStream. TypeError [ERR_INVALID_URL]: Invalid URL: 
[2022-08-07 23:36:00.152] error: [strapi-plugin-sitemap]: Something went wrong while trying to build the SitemapStream. TypeError [ERR_INVALID_URL]: Invalid URL: 
[2022-08-07 23:37:00.161] error: [strapi-plugin-sitemap]: Something went wrong while trying to build the SitemapStream. TypeError [ERR_INVALID_URL]: Invalid URL: 
[2022-08-07 23:38:00.151] error: [strapi-plugin-sitemap]: Something went wrong while trying to build the SitemapStream. TypeError [ERR_INVALID_URL]: Invalid URL: 
[2022-08-07 23:38:10.917] info: File created: /srv/app/docker-compose.yaml
Starting the compilation for TypeScript files in /srv/app
The server is restarting

[2022-08-07 23:39:23.680] info: --------  MIGRATION STARTED  --------
[2022-08-07 23:39:23.702] warn: No migration directory found.
[2022-08-07 23:39:23.703] info: --------  MIGRATION FINISHED  --------
[2022-08-07 23:39:23.741] info: [website builder] manual trigger enabled

 Project information

┌────────────────────┬──────────────────────────────────────────────────┐
│ Time               │ Sun Aug 07 2022 23:39:24 GMT+0000 (Coordinated … │
│ Launched in        │ 27742 ms                                         │
│ Environment        │ development                                      │
│ Process PID        │ 95                                               │
│ Version            │ 4.3.2 (node v14.20.0)                            │
│ Edition            │ Community                                        │
└────────────────────┴──────────────────────────────────────────────────┘

 Actions available

Welcome back!
To manage your project 🚀, go to the administration panel at:
http://localhost:1337/admin

To access the server ⚡️, go to:
http://localhost:1337

[2022-08-07 23:40:00.154] error: [strapi-plugin-sitemap]: Something went wrong while trying to build the SitemapStream. TypeError [ERR_INVALID_URL]: Invalid URL: 
[2022-08-07 23:41:00.162] error: [strapi-plugin-sitemap]: Something went wrong while trying to build the SitemapStream. TypeError [ERR_INVALID_URL]: Invalid URL: 
[2022-08-07 23:42:00.163] error: [strapi-plugin-sitemap]: Something went wrong while trying to build the SitemapStream. TypeError [ERR_INVALID_URL]: Invalid URL: 
[2022-08-07 23:43:00.145] error: [strapi-plugin-sitemap]: Something went wrong while trying to build the SitemapStream. TypeError [ERR_INVALID_URL]: Invalid URL: 
[2022-08-07 23:44:00.157] error: [strapi-plugin-sitemap]: Something went wrong while trying to build the SitemapStream. TypeError [ERR_INVALID_URL]: Invalid URL: 
[2022-08-07 23:45:00.184] error: [strapi-plugin-sitemap]: Something went wrong while trying to build the SitemapStream. TypeError [ERR_INVALID_URL]: Invalid URL: 
[2022-08-07 23:46:00.220] error: [strapi-plugin-sitemap]: Something went wrong while trying to build the SitemapStream. TypeError [ERR_INVALID_URL]: Invalid URL: 
[2022-08-07 23:47:00.184] error: [strapi-plugin-sitemap]: Something went wrong while trying to build the SitemapStream. TypeError [ERR_INVALID_URL]: Invalid URL: 
[2022-08-07 23:48:00.174] error: [strapi-plugin-sitemap]: Something went wrong while trying to build the SitemapStream. TypeError [ERR_INVALID_URL]: Invalid URL: 
[2022-08-07 23:49:00.134] error: [strapi-plugin-sitemap]: Something went wrong while trying to build the SitemapStream. TypeError [ERR_INVALID_URL]: Invalid URL: 
[2022-08-07 23:50:00.162] error: [strapi-plugin-sitemap]: Something went wrong while trying to build the SitemapStream. TypeError [ERR_INVALID_URL]: Invalid URL: 
    at Object.createSitemap (/srv/app/node_modules/strapi-plugin-sitemap/server/services/core.js:248:11)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason:
Error
    at Object.createSitemap (/srv/app/node_modules/strapi-plugin-sitemap/server/services/core.js:248:11)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason:
Error
    at Object.createSitemap (/srv/app/node_modules/strapi-plugin-sitemap/server/services/core.js:248:11)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason:
Error
    at Object.createSitemap (/srv/app/node_modules/strapi-plugin-sitemap/server/services/core.js:248:11)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason:
Error
    at Object.createSitemap (/srv/app/node_modules/strapi-plugin-sitemap/server/services/core.js:248:11)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason:
Error
    at Object.createSitemap (/srv/app/node_modules/strapi-plugin-sitemap/server/services/core.js:248:11)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason:
Error
    at Object.createSitemap (/srv/app/node_modules/strapi-plugin-sitemap/server/services/core.js:248:11)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason:
Error
    at Object.createSitemap (/srv/app/node_modules/strapi-plugin-sitemap/server/services/core.js:248:11)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason:
Error
    at Object.createSitemap (/srv/app/node_modules/strapi-plugin-sitemap/server/services/core.js:248:11)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)

```

This altogether 

### Steps to reproduce the behavior

1. Go Sitemap.
2. Go to the container logs(either in terminal or docker desktop).
3. Scroll down to find the error.
4. See an error

### Expected behavior

We should not get any error in both the **docker logs** and the website.

### Screenshots

![sitemaperror](https://user-images.githubusercontent.com/5034215/183316543-dfaecd10-3b5c-4141-94e9-77eb48b4feae.gif)

### System

- Node.js version: 4.3.2 (node v14.20.0) 
- Strapi version: 4.3.2
- Plugin version: 2.0.8
- Database: PostgreSQL 13.7
- Operating system: Alpine Linux v3.16

**Comment by boazpoolman** [comment]
Hmm that's odd.
It is trying to generate the sitemap, though not all the required settings are set.
And it's mostly odd that it does this without you clicking on the generate sitemap button.

I'll try to look in to this and reproduce the issue.

Did I see correctly you are using typescript for this v4.3 project?

**Comment by SalahAdDin** [comment]
> Hmm that's odd. It is trying to generate the sitemap, though not all the required settings are set. And it's mostly odd that it does this without you clicking on the generate sitemap button.
> 
> I'll try to look in to this and reproduce the issue.
> 
> Did I see correctly you are using typescript for this v4.3 project?

Exactly, I'm working with **Typescript.**

**Comment by SalahAdDin** [comment]
> Hi @SalahAdDin,
> 
> I was unable to reproduce the issue. Though looking at the I'm seeing that you try to generate the sitemap every 1 minute.
> 
> Do you have some kind of cron setup? To generate the sitemap every minute?

Actually, no:
```
  "* * * * 7": ({ strapi }) => {
    strapi.plugin("sitemap").service("core").createSitemap();
  },
```

**Comment by boazpoolman** [comment]
Ah allright. So you do have cron setup to generate the sitemap.
Though you have not set the hostname yet. Then indeed it will give an error.

Please go through the settings form before trying to generate the sitemap.

**Comment by SalahAdDin** [comment]
> Ah allright. So you do have cron setup to generate the sitemap. Though you have not set the hostname yet. Then indeed it will give an error.
> 
> Please go through the settings form before trying to generate the sitemap.

can be set `localhost` by default for development?

**Comment by marcin-piechaczek** [comment]
I have a similar problem trying to generate a sitemap for 40k pages, is there a way to undo all changes on the database? Now my strapi is working extremely slow.

**Comment by boazpoolman** [comment]
It could. But then again you would need to set custom URLs or URL bundles to even have it make sense to generate the sitemap. So I don't see a reason to have a default hostname.

**Comment by boazpoolman** [comment]
I'm gonna close this issue as it's not so much an issue with this plugin, but rather with the implementation of it.

Please feel free to re-open the issue if you still have any questions.
